import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar";
import { Footer } from "@/components/custom";

export const metadata: Metadata = {
  title: "Far From Home ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-8xl mx-auto">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
